# Generated by Django 5.2.11 on 2026-03-08 15:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва Сервісу"),
                ),
                ("content", tinymce.models.HTMLField(verbose_name="Опис сервісу")),
            ],
            options={
                "verbose_name": "Сервіс",
                "verbose_name_plural": "Сервіси",
            },
        ),
    ]
