# Generated by Django 5.2.11 on 2026-04-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "h1",
                    models.CharField(
                        default="Services",
                        max_length=200,
                        verbose_name="Заголовок сторінки",
                    ),
                ),
                (
                    "sub_title",
                    models.CharField(
                        blank=True,
                        default="Additional Services",
                        max_length=200,
                        verbose_name="Заголовок сторінки",
                    ),
                ),
                (
                    "sub_text",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="Доп текст"
                    ),
                ),
                (
                    "img_main",
                    models.ImageField(upload_to="service/", verbose_name="Зображення"),
                ),
                (
                    "img_main_alt",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Опис для зображення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Послуги сторінка",
                "verbose_name_plural": "Послуги сторінка",
            },
        ),
        migrations.CreateModel(
            name="ServicePageExtraServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_title",
                    models.CharField(
                        default="Services", max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "option_text",
                    models.CharField(
                        default="Services", max_length=200, verbose_name="Текст"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra",
                        to="services.servicepage",
                        verbose_name="Доп послуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп послуга",
                "verbose_name_plural": "Доп послуги",
                "ordering": ["order"],
            },
        ),
    ]
