# Generated by Django 5.2.11 on 2026-04-19 22:00

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicepage_servicepageextraservices"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="img_main",
            field=models.ImageField(
                default="", upload_to="service/", verbose_name="Зображення"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="img_main_alt",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Опис для зображення"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="option_1",
            field=models.CharField(
                default="", max_length=100, verbose_name="Доп інфо 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="option_2",
            field=models.CharField(
                default="", max_length=100, verbose_name="Доп інфо 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="option_3",
            field=models.CharField(
                default="", max_length=100, verbose_name="Доп інфо 3"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="sub_text",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Доп текст"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="text",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Доп текст"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Назва сервісу"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Опис проекту"),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="ServiceCapabilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Назва"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Інформація",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "сapabilities",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="сapabilities",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Можливість",
                "verbose_name_plural": "Можливості",
            },
        ),
        migrations.CreateModel(
            name="ServiceDetailsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="", max_length=100, verbose_name="Параметр"
                    ),
                ),
                (
                    "feture",
                    models.CharField(
                        default="", max_length=100, verbose_name="Значення"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "s_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп інформація",
                "verbose_name_plural": "Доп інформація",
            },
        ),
        migrations.CreateModel(
            name="ServiceMethodology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Назва"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Інформація",
                    ),
                ),
                (
                    "option_1",
                    models.CharField(max_length=200, verbose_name="Доп інфо 1"),
                ),
                (
                    "option_2",
                    models.CharField(max_length=200, verbose_name="Доп інфо 2"),
                ),
                (
                    "option_3",
                    models.CharField(max_length=200, verbose_name="Доп інфо 3"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "methodology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methodology",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Методологія",
                "verbose_name_plural": "Методологіі",
            },
        ),
    ]
