# Generated by Django 5.2.11 on 2026-04-28 14:00

import functools
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_service_seo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="img_main",
            field=models.ImageField(
                upload_to=functools.partial(
                    services.models.upload_to_folder, *(), **{"folder": "service"}
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="servicedetailsdata",
            name="feture",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Значення"
            ),
        ),
        migrations.AlterField(
            model_name="servicedetailsdata",
            name="key",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Параметр"
            ),
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="img_main",
            field=models.ImageField(
                upload_to=functools.partial(
                    services.models.upload_to_folder, *(), **{"folder": "service"}
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="servicepageextraservices",
            name="option_text",
            field=models.CharField(
                blank=True, default="Services", max_length=200, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="servicepageextraservices",
            name="option_title",
            field=models.CharField(
                blank=True, default="Services", max_length=200, verbose_name="Заголовок"
            ),
        ),
    ]
