# Generated by Django 5.2.11 on 2026-02-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("text", models.TextField(verbose_name="Text")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer",
            },
        ),
    ]
