# Generated by Django 5.2.11 on 2026-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footer",
            name="text",
        ),
        migrations.RemoveField(
            model_name="footer",
            name="title",
        ),
        migrations.AddField(
            model_name="footer",
            name="email",
            field=models.EmailField(
                default="default@test.com", max_length=255, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="footer",
            name="phone",
            field=models.CharField(
                default="+38 000 000 00 00", max_length=50, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="footer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
