# Generated by Django 5.2.11 on 2026-03-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_footer_text_remove_footer_title_footer_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Імʼя клієнта")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("message", models.TextField(verbose_name="Повідомлення")),
            ],
            options={
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
            },
        ),
        migrations.CreateModel(
            name="ContactsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адреса")),
                (
                    "city",
                    models.TextField(
                        blank=True, verbose_name="Місто, Область, Поштовий індекс"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер телефону"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email адреса"
                    ),
                ),
                (
                    "google_maps_url",
                    models.TextField(blank=True, verbose_name="Google Maps посилання"),
                ),
            ],
            options={
                "verbose_name": "Контактна інформація",
                "verbose_name_plural": "Контактна інформація",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Twitter (X)",
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Instagram"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Linked In"
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="YouTube"
                    ),
                ),
            ],
            options={
                "verbose_name": "Соц-мережі",
                "verbose_name_plural": "Соц-мережі",
            },
        ),
    ]
