# Generated by Django 5.2.11 on 2026-03-04 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_contactmessages_contactsdata_socialmedia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Footer",
        ),
        migrations.AlterModelOptions(
            name="contactsdata",
            options={
                "verbose_name": "Контактну інформацію",
                "verbose_name_plural": "Контактна інформація",
            },
        ),
    ]
