# Generated by Django 5.2.11 on 2026-03-04 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_footer_alter_contactsdata_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessages",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата повідомлення",
            ),
            preserve_default=False,
        ),
    ]
