# Generated by Django 5.2.11 on 2026-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_contactmessages_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessages",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
            },
        ),
        migrations.AddField(
            model_name="contactmessages",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
    ]
