# Generated by Django 5.2.11 on 2026-03-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_contactmessages_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageSeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="SEO: Title сторінки"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="SEO: Meta description"),
                ),
                ("h1", models.CharField(max_length=255, verbose_name="H1 заголовок")),
            ],
            options={
                "verbose_name": "Головна сторінка",
                "verbose_name_plural": "Головна сторінка",
            },
        ),
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="home_slider/", verbose_name="Фото слайду"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=355, verbose_name="Текст на слайді"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="main.homepageseo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайдер головної сторінки",
                "ordering": ["order"],
            },
        ),
    ]
