# Generated by Django 5.2.11 on 2026-03-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_homepageseo_homeslider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepageseo",
            options={
                "verbose_name": "Головну сторінку",
                "verbose_name_plural": "Головна сторінка",
            },
        ),
    ]
