# Generated by Django 5.2.11 on 2026-03-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_homepageseo_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeslider",
            name="text",
        ),
    ]
