# Generated by Django 5.2.11 on 2026-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_homeslider_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="alt",
            field=models.CharField(default="alt", max_length=300, verbose_name="Alt"),
            preserve_default=False,
        ),
    ]
