# Generated by Django 5.2.11 on 2026-03-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_homeslider_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="alt_mobile",
            field=models.CharField(
                default="alt", max_length=300, verbose_name="Alt (mobile)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeslider",
            name="image_mobile",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="home_slider/",
                verbose_name="Фото слайду (mobile)",
            ),
        ),
    ]
