# Generated by Django 5.2.11 on 2026-03-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_homeslider_alt_mobile_homeslider_image_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeslider",
            name="alt_mobile",
        ),
    ]
