# Generated by Django 5.2.11 on 2026-03-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_homeslider_alt_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h1", models.CharField(max_length=255, verbose_name="H1 заголовок")),
            ],
            options={
                "verbose_name": "Головну сторінку",
                "verbose_name_plural": "Головна сторінка",
            },
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slides",
                to="main.homepage",
            ),
        ),
        migrations.DeleteModel(
            name="HomePageSeo",
        ),
    ]
