# Generated by Django 5.2.11 on 2026-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_homepage_alter_homeslider_page_delete_homepageseo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h1", models.CharField(max_length=255, verbose_name="H1 заголовок")),
                ("h2", models.CharField(max_length=255, verbose_name="H2 заголовок")),
                (
                    "history_text",
                    models.TextField(
                        blank=True, default="", verbose_name="Істрорія Компанії"
                    ),
                ),
                (
                    "history_img",
                    models.ImageField(
                        upload_to="home_about/", verbose_name="Зображення блок істроія"
                    ),
                ),
                ("history_video", models.CharField(verbose_name="Ютуб посилання")),
            ],
            options={
                "verbose_name": "Сторінку про компанію",
                "verbose_name_plural": "Сторінка про компанію",
            },
        ),
    ]
