# Generated by Django 5.2.11 on 2026-03-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_aboutpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="h2",
            field=models.CharField(max_length=255, verbose_name="Істрорія заголовок"),
        ),
        migrations.CreateModel(
            name="StatsAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Заголовок (статистика)",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Підзаголовок (статистика)",
                    ),
                ),
                (
                    "clients_number",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        verbose_name="Кіл-сть клієнтів (статистика)",
                    ),
                ),
                (
                    "projects_number",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        verbose_name="Кіл-сть проектів (статистика)",
                    ),
                ),
                (
                    "support_h_number",
                    models.IntegerField(
                        blank=True,
                        default=100,
                        verbose_name="Кіл-сть годин підтримки (статистика)",
                    ),
                ),
                (
                    "workers_number",
                    models.IntegerField(
                        blank=True,
                        default=100,
                        verbose_name="Кіл-сть співробітників (статистика)",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="main.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розділ статистика",
                "verbose_name_plural": "Розділ статистики",
            },
        ),
    ]
