# Generated by Django 5.2.11 on 2026-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_aboutpage_h2_statsaboutpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="history_img",
            field=models.ImageField(upload_to="home_about/", verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="history_video",
            field=models.URLField(blank=True, verbose_name="Ютуб посилання"),
        ),
        migrations.AlterField(
            model_name="statsaboutpage",
            name="clients_number",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="Кіл-сть клієнтів (статистика)"
            ),
        ),
        migrations.AlterField(
            model_name="statsaboutpage",
            name="projects_number",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="Кіл-сть проектів (статистика)"
            ),
        ),
        migrations.AlterField(
            model_name="statsaboutpage",
            name="support_h_number",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                verbose_name="Кіл-сть годин підтримки (статистика)",
            ),
        ),
        migrations.AlterField(
            model_name="statsaboutpage",
            name="workers_number",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                verbose_name="Кіл-сть співробітників (статистика)",
            ),
        ),
    ]
