# Generated by Django 5.2.11 on 2026-03-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_aboutpage_history_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="h2",
            field=models.CharField(max_length=255, verbose_name="Історія заголовок"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="history_text",
            field=models.TextField(
                blank=True, default="", verbose_name="Історія Компанії"
            ),
        ),
        migrations.AlterField(
            model_name="statsaboutpage",
            name="page",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="main.aboutpage",
            ),
        ),
    ]
