# Generated by Django 5.2.11 on 2026-03-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_aboutpage_h2_alter_aboutpage_history_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="clients_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="Кіл-сть клієнтів (статистика)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="projects_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="Кіл-сть проектів (статистика)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="subtitle_statistics",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Підзаголовок (статистика)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="support_h_number_statistics",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                verbose_name="Кіл-сть годин підтримки (статистика)",
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="title_statistics",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок (статистика)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="workers_number_statistics",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                verbose_name="Кіл-сть співробітників (статистика)",
            ),
        ),
        migrations.DeleteModel(
            name="StatsAboutPage",
        ),
    ]
