# Generated by Django 5.2.11 on 2026-03-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_aboutpage_clients_number_statistics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="statistics_img",
            field=models.ImageField(
                default="", upload_to="home_about/", verbose_name="Зображення перше"
            ),
            preserve_default=False,
        ),
    ]
