# Generated by Django 5.2.11 on 2026-03-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_aboutpage_statistics_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="clients_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="Клієнти"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="projects_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=10, verbose_name="Проекти"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="subtitle_statistics",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Підзаголовок"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="support_h_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=100, verbose_name="Години підтримки"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="title_statistics",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="workers_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=100, verbose_name="Робітник"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="facebook",
            field=models.URLField(
                blank=True, default="", max_length=150, verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="instagram",
            field=models.URLField(
                blank=True, default="", max_length=150, verbose_name="Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="linkedin",
            field=models.URLField(
                blank=True, default="", max_length=150, verbose_name="Linked In"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="twitter",
            field=models.URLField(
                blank=True, default="", max_length=150, verbose_name="Twitter (X)"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="youtube",
            field=models.URLField(blank=True, default="", verbose_name="YouTube"),
        ),
    ]
