# Generated by Django 5.2.11 on 2026-03-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_aboutpage_clients_number_statistics_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmedia",
            options={
                "verbose_name": "Соціальні мережі",
                "verbose_name_plural": "Соціальні мережі",
            },
        ),
        migrations.CreateModel(
            name="TeamAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=150, verbose_name="Імʼя")),
                (
                    "team_position",
                    models.CharField(max_length=150, verbose_name="Посада"),
                ),
                (
                    "team_description",
                    models.CharField(
                        max_length=350, verbose_name="детальна інформація"
                    ),
                ),
                ("twitter", models.URLField(blank=True, verbose_name="twitter")),
                ("facebook", models.URLField(blank=True, verbose_name="facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="instagram")),
                ("linkedin", models.URLField(blank=True, verbose_name="linkedin")),
                (
                    "team_img",
                    models.ImageField(
                        upload_to="home_about_team/", verbose_name="Зображення"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team",
                        to="main.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учасник команди",
                "verbose_name_plural": "Учасники команди",
            },
        ),
    ]
