# Generated by Django 5.2.11 on 2026-03-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_socialmedia_options_teamaboutpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamaboutpage",
            name="team_description",
            field=models.CharField(max_length=350, verbose_name="Детальна інформація"),
        ),
        migrations.CreateModel(
            name="TestimonialsAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "testimonials_name",
                    models.CharField(max_length=150, verbose_name="Імʼя"),
                ),
                (
                    "testimonials_position",
                    models.CharField(max_length=150, verbose_name="Посада"),
                ),
                ("testimonials_message", models.CharField(verbose_name="Відгук")),
                (
                    "testimonials_img",
                    models.ImageField(
                        upload_to="home_about_testimonials/", verbose_name="Аватар"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="main.aboutpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
            },
        ),
    ]
