# Generated by Django 5.2.11 on 2026-04-15 09:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_teamaboutpage_team_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h1", models.CharField(max_length=255, verbose_name="H1 заголовок")),
                ("content", tinymce.models.HTMLField(verbose_name="Опис проекту")),
            ],
            options={
                "verbose_name": "Відгук",
                "verbose_name_plural": "Відгуки",
            },
        ),
    ]
