# Generated by Django 5.2.11 on 2026-04-15 10:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_terms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("h1", models.CharField(max_length=255, verbose_name="H1 заголовок")),
                ("content", tinymce.models.HTMLField(verbose_name="Опис проекту")),
            ],
            options={
                "verbose_name": "Політика конфіденційності",
                "verbose_name_plural": "Політика конфіденційності",
            },
        ),
        migrations.AlterModelOptions(
            name="terms",
            options={
                "verbose_name": "Умови обслуговування",
                "verbose_name_plural": "Умови обслуговування",
            },
        ),
    ]
