# Generated by Django 5.2.11 on 2026-04-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_privacy_alter_terms_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeSlider",
        ),
    ]
