# Generated by Django 5.2.11 on 2026-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_delete_homeslider"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_img",
            field=models.ImageField(
                default="",
                upload_to="home_main/",
                verbose_name="Вступ: Зображення (1920\xa0×\xa01080)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_img_alt",
            field=models.CharField(
                default="",
                max_length=300,
                verbose_name="Вступ: Зображення - опис (alt)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_projects_completed",
            field=models.CharField(
                default="", max_length=10, verbose_name="Вступ: завершено проектів"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_satisfied_clients",
            field=models.CharField(
                default="", max_length=10, verbose_name="Вступ: кількість клієнтів"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=models.TextField(
                default="", verbose_name="Вступ: текст под заголовком"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_video",
            field=models.URLField(default="", verbose_name="Ютуб посилання"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_years_experience",
            field=models.CharField(
                default="", max_length=10, verbose_name="Вступ: роки на ринку"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="h1",
            field=models.CharField(max_length=255, verbose_name="Вступ: H1 заголовок"),
        ),
    ]
