# Generated by Django 5.2.11 on 2026-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_homepage_hero_img_homepage_hero_img_alt_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutpage",
            options={
                "verbose_name": "Сторінку про компанію",
                "verbose_name_plural": "Про компанію",
            },
        ),
        migrations.AlterModelOptions(
            name="contactsdata",
            options={
                "verbose_name": "Контактну інформацію",
                "verbose_name_plural": "Контакти",
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "verbose_name": "Головну сторінку",
                "verbose_name_plural": "Головна",
            },
        ),
        migrations.AlterModelOptions(
            name="privacy",
            options={
                "verbose_name": "Політика конфіденційності",
                "verbose_name_plural": "Конфіденційність",
            },
        ),
        migrations.AlterModelOptions(
            name="terms",
            options={
                "verbose_name": "Умови обслуговування",
                "verbose_name_plural": "Сторінка умови",
            },
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_text",
            field=models.TextField(verbose_name="Вступ: текст під заголовком H1"),
        ),
    ]
