# Generated by Django 5.2.11 on 2026-04-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_aboutpage_options_alter_contactsdata_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamaboutpage",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="teamaboutpage",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="teamaboutpage",
            name="twitter",
        ),
        migrations.AddField(
            model_name="teamaboutpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="teamaboutpage",
            name="h1",
            field=models.CharField(
                default="", max_length=255, verbose_name="H1 заголовок"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamaboutpage",
            name="option_1",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Доп інфо 1"
            ),
        ),
        migrations.AddField(
            model_name="teamaboutpage",
            name="option_2",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Доп інфо 2"
            ),
        ),
        migrations.AddField(
            model_name="teamaboutpage",
            name="phone",
            field=models.CharField(default="", max_length=15, verbose_name="Телефон"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teamaboutpage",
            name="team_description",
            field=models.CharField(
                blank=True, max_length=350, verbose_name="Детальна інформація"
            ),
        ),
    ]
