# Generated by Django 5.2.11 on 2026-04-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_remove_teamaboutpage_facebook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="h1",
        ),
        migrations.RemoveField(
            model_name="teamaboutpage",
            name="h1",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="h1_about",
            field=models.CharField(
                default="", max_length=255, verbose_name="H1 сторінка про компанію"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="h1_team",
            field=models.CharField(
                default="", max_length=255, verbose_name="H1 сторінка команда"
            ),
            preserve_default=False,
        ),
    ]
