# Generated by Django 5.2.11 on 2026-04-17 12:55

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_remove_aboutpage_h1_remove_teamaboutpage_h1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="clients_number_statistics",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="history_img",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="subtitle_statistics",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="support_h_number_statistics",
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="title_statistics",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="alt_img_left",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt текст (left)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="alt_img_right",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Alt текст (right)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="history_img_left",
            field=models.ImageField(
                null=True, upload_to="home_about/", verbose_name="Зображення (left)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="history_img_right",
            field=models.ImageField(
                null=True, upload_to="home_about/", verbose_name="Зображення (right)"
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="years_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Кількість років"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="history_text",
            field=tinymce.models.HTMLField(verbose_name="Історія Компанії"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="projects_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Кількість Проектів"
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="workers_number_statistics",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Кількість працівників"
            ),
        ),
        migrations.CreateModel(
            name="AboutImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="home_about/", verbose_name="Зображення сертифікатів"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt текст"
                    ),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.aboutpage",
                        verbose_name="Блок About",
                    ),
                ),
            ],
        ),
    ]
