# Generated by Django 5.2.11 on 2026-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_remove_aboutpage_clients_number_statistics_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Зображення",
                "verbose_name_plural": "Зображення",
            },
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="statistics_img",
        ),
        migrations.AddField(
            model_name="aboutimage",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
