# Generated by Django 5.2.11 on 2026-04-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_aboutimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="awards_certif",
            field=models.TextField(default="", verbose_name="Сертифікати: Кількість"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="img_certif",
            field=models.ImageField(
                default="",
                upload_to="home_main/",
                verbose_name="Сертифікати: Зображення (1920\xa0×\xa01080)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="img_certif_alt",
            field=models.CharField(
                default="",
                max_length=300,
                verbose_name="Сертифікати: Зображення - опис (alt)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="option_1",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Підтримка: доп 1"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="option_2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Підтримка: доп 2"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="option_3",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Підтримка: доп 3"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_text_certif",
            field=models.CharField(
                default="",
                max_length=500,
                verbose_name="Сертифікати: Доп текст розділу",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_text_portfolio",
            field=models.CharField(
                default="", max_length=500, verbose_name="Проекти: Доп текст розділу"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_text_services",
            field=models.CharField(
                default="", max_length=500, verbose_name="Послуги: Доп текст розділу"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_text_team",
            field=models.CharField(
                default="", max_length=500, verbose_name="Команда: Доп текст розділу"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_title_certif",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Сертифікати: Заголовок розділу",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_title_portfolio",
            field=models.CharField(
                default="", max_length=255, verbose_name="Проекти: Заголовок розділу"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_title_services",
            field=models.CharField(
                default="", max_length=255, verbose_name="Послуги: Заголовок розділу"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="sub_title_team",
            field=models.CharField(
                default="", max_length=255, verbose_name="Команда: Заголовок розділу"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="text_certif",
            field=models.TextField(default="", verbose_name="Сертифікати: Текст"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="text_certif_img",
            field=models.TextField(
                default="", verbose_name="Сертифікати: Текст блок з зображенням"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="text_quote",
            field=models.TextField(default="", verbose_name="Підтримка: Текст"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_certif",
            field=models.CharField(
                default="", max_length=255, verbose_name="Сертифікати: Заголовок"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_certif_img",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Сертифікати: Заголовок блок з зображенням",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="title_quote",
            field=models.CharField(
                default="", max_length=255, verbose_name="Підтримка: Заголовок"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_projects_completed",
            field=models.CharField(
                max_length=10, verbose_name="Вступ: Завершено проектів"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_satisfied_clients",
            field=models.CharField(
                max_length=10, verbose_name="Вступ: Кількість клієнтів"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_text",
            field=models.TextField(verbose_name="Вступ: Текст під заголовком H1"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_years_experience",
            field=models.CharField(max_length=10, verbose_name="Вступ: Роки на ринку"),
        ),
    ]
