# Generated by Django 5.2.11 on 2026-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_homepage_awards_certif_homepage_img_certif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonialsaboutpage",
            name="testimonials_company",
            field=models.CharField(default="", max_length=150, verbose_name="Компанія"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="awards_certif",
            field=models.CharField(verbose_name="Сертифікати: Кількість"),
        ),
        migrations.AlterField(
            model_name="testimonialsaboutpage",
            name="testimonials_message",
            field=models.TextField(verbose_name="Відгук"),
        ),
    ]
