# Generated by Django 5.2.11 on 2026-04-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_testimonialsaboutpage_testimonials_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageCertifCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Назва сертифікату"),
                ),
                (
                    "sub_title",
                    models.CharField(max_length=255, verbose_name="Доп інформація"),
                ),
                ("text", models.TextField(max_length=600, verbose_name="Опис")),
                (
                    "img",
                    models.ImageField(
                        null=True,
                        upload_to="home_about/",
                        verbose_name="Зображення сертифікату",
                    ),
                ),
                (
                    "alt_img",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Alt текст для зображення",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certif",
                        to="main.homepage",
                        verbose_name="Блок Добавити Сертифікат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертифікат",
                "verbose_name_plural": "Сертифікати",
                "ordering": ["order"],
            },
        ),
    ]
