# Generated by Django 5.2.11 on 2026-04-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_homepagecertifcreator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="home_gallery/", verbose_name="Фото - галерея"
                    ),
                ),
                (
                    "alt_img",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Alt текст"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото галерея",
                "verbose_name_plural": "Фото галерея",
            },
        ),
    ]
