# Generated by Django 5.2.11 on 2026-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="text",
            field=models.CharField(default="", max_length=500, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="Заголовок"
            ),
        ),
    ]
