# Generated by Django 5.2.11 on 2026-04-28 14:00

import functools
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_gallery_text_gallery_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutimage",
            name="image",
            field=models.ImageField(
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Зображення сертифікатів",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="history_img_left",
            field=models.ImageField(
                null=True,
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Зображення (left)",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="history_img_right",
            field=models.ImageField(
                null=True,
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Зображення (right)",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="img",
            field=models.ImageField(
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Фото - галерея",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_img",
            field=models.ImageField(
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Вступ: Зображення (1920\xa0×\xa01080)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="img_certif",
            field=models.ImageField(
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Сертифікати: Зображення (1920\xa0×\xa01080)",
            ),
        ),
        migrations.AlterField(
            model_name="homepagecertifcreator",
            name="img",
            field=models.ImageField(
                null=True,
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Зображення сертифікату",
            ),
        ),
        migrations.AlterField(
            model_name="teamaboutpage",
            name="team_img",
            field=models.ImageField(
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="testimonialsaboutpage",
            name="testimonials_img",
            field=models.ImageField(
                upload_to=functools.partial(
                    main.models.upload_to_folder, *(), **{"folder": "home_main"}
                ),
                verbose_name="Аватар",
            ),
        ),
    ]
