# Generated by Django 5.2.11 on 2026-03-11 13:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва Проекту"),
                ),
                ("content", tinymce.models.HTMLField(verbose_name="Опис проекту")),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Портфоліо",
                "verbose_name_plural": "Портфоліо",
            },
        ),
    ]
