# Generated by Django 5.2.11 on 2026-04-19 12:39

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="content_brif",
            field=models.TextField(
                default="", max_length=500, verbose_name="Опис проекту (коротко)"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="img",
            field=models.ImageField(
                default="", upload_to="portfolio/", verbose_name="Зображення"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="img_alt",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Опис для зображення"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="img_main",
            field=models.ImageField(
                default="", upload_to="portfolio/", verbose_name="Зображення головне"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="img_main_alt",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Опис для зображення"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="location",
            field=models.CharField(
                default="", max_length=100, verbose_name="Місце розташування"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="option_1",
            field=models.CharField(default="", max_length=50, verbose_name="Доп інфо"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="option_2",
            field=models.CharField(
                default="", max_length=50, verbose_name="Срок виконання"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="option_3",
            field=models.CharField(
                default="", max_length=50, verbose_name="Доп інфо 1"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="option_4",
            field=models.CharField(
                default="", max_length=50, verbose_name="Доп інфо 2"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новий"),
                    ("progress", "В роботі"),
                    ("done", "Завершено"),
                ],
                default="new",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="type",
            field=models.CharField(
                default="", max_length=100, verbose_name="Тип Проекту"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Назва Проекту"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="PortfolioDetailsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="", max_length=100, verbose_name="Назва Проекту"
                    ),
                ),
                (
                    "feture",
                    models.CharField(
                        default="", max_length=100, verbose_name="Тип Проекту"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "p_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тех інформація",
                "verbose_name_plural": "Тех інформація",
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="portfolio/", verbose_name="Портфоліо фото"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt текст"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "p_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.portfolio",
                        verbose_name="Блок фотогалерея",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення",
                "verbose_name_plural": "Зображення",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Назва Проекту"
                    ),
                ),
                (
                    "doc_content",
                    tinymce.models.HTMLField(verbose_name="Технічна документація"),
                ),
                (
                    "img_doc",
                    models.ImageField(
                        upload_to="portfolio/", verbose_name="Зображення документація"
                    ),
                ),
                (
                    "img_doc_alt",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Опис для зображення"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "p_tech_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тех документація",
                "verbose_name_plural": "Тех документація",
            },
        ),
    ]
