# Generated by Django 5.2.11 on 2026-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolio_content_brif_portfolio_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicaldetails",
            name="doc_slug",
            field=models.SlugField(default="slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portfoliodetailsdata",
            name="feture",
            field=models.CharField(default="", max_length=100, verbose_name="Значення"),
        ),
        migrations.AlterField(
            model_name="portfoliodetailsdata",
            name="key",
            field=models.CharField(default="", max_length=100, verbose_name="Параметр"),
        ),
    ]
