# Generated by Django 5.2.11 on 2026-04-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_technicaldetails_doc_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technicaldetails",
            old_name="doc_slug",
            new_name="slug",
        ),
    ]
