# Generated by Django 5.2.11 on 2026-04-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_rename_doc_slug_technicaldetails_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "h1",
                    models.CharField(
                        default="", max_length=200, verbose_name="Заголовок сторінки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Портфоліо сторінка",
                "verbose_name_plural": "Портфоліо сторінка",
            },
        ),
    ]
