# Generated by Django 5.2.11 on 2026-04-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_portfoliopage"),
        ("seo", "0003_pageseo_slug_alter_pageseo_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="seo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio",
                to="seo.pageseo",
            ),
        ),
    ]
