# Generated by Django 5.2.11 on 2026-04-28 14:10

import django.db.models.deletion
import functools
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_portfolio_seo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="content_brif",
            field=models.TextField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Опис проекту (коротко)",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="img",
            field=models.ImageField(
                upload_to=functools.partial(
                    portfolio.models.upload_to_folder, *(), **{"folder": "portfolio"}
                ),
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="img_main",
            field=models.ImageField(
                upload_to=functools.partial(
                    portfolio.models.upload_to_folder, *(), **{"folder": "portfolio"}
                ),
                verbose_name="Зображення головне",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Місце розташування",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Назва Проекту"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="option_1",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Доп інфо"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="option_2",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Срок виконання"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="option_3",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Доп інфо 1"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="option_4",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Доп інфо 2"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Тип Проекту"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliodetailsdata",
            name="feture",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Значення"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliodetailsdata",
            name="key",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Параметр"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioimage",
            name="image",
            field=models.ImageField(
                upload_to=functools.partial(
                    portfolio.models.upload_to_folder, *(), **{"folder": "portfolio"}
                ),
                verbose_name="Портфоліо фото",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="h1",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Заголовок сторінки",
            ),
        ),
        migrations.AlterField(
            model_name="technicaldetails",
            name="doc_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Назва Проекту"
            ),
        ),
        migrations.AlterField(
            model_name="technicaldetails",
            name="img_doc",
            field=models.ImageField(
                upload_to=functools.partial(
                    portfolio.models.upload_to_folder, *(), **{"folder": "portfolio"}
                ),
                verbose_name="Зображення документація",
            ),
        ),
        migrations.AlterField(
            model_name="technicaldetails",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="PortfolioAddInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extr_key",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Параметр"
                    ),
                ),
                (
                    "extr_feture",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Значення"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "add_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_data",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп інформація",
                "verbose_name_plural": "Доп інформація",
            },
        ),
    ]
