# Generated by Django 5.2.11 on 2026-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_portfolio_content_brif_alter_portfolio_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioaddinfo",
            name="extr_feture_1",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Значення"
            ),
        ),
        migrations.AddField(
            model_name="portfolioaddinfo",
            name="extr_key_1",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Параметр"
            ),
        ),
    ]
