# Generated by Django 5.2.11 on 2026-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Головна сторінка"),
                            ("about", "Про компанію"),
                            ("contact", "Контакти"),
                            ("services", "Сторінка сервісів"),
                            ("portfolio", "Портфоліо"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Сторінка",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="SEO title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Meta description"),
                ),
                ("canonical", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/"),
                ),
            ],
            options={
                "verbose_name": "SEO сторінка",
                "verbose_name_plural": "SEO сторінки",
            },
        ),
    ]
