# Generated by Django 5.2.11 on 2026-03-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pageseo",
            options={
                "verbose_name": "SEO сторінку",
                "verbose_name_plural": "SEO сторінки",
            },
        ),
    ]
