# Generated by Django 5.2.11 on 2026-04-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_alter_pageseo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageseo",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Головна сторінка"),
                    ("about", "Про компанію"),
                    ("contact", "Контакти"),
                    ("services", "Сторінка Послуг"),
                    ("portfolio", "Портфоліо"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Сторінка",
            ),
        ),
    ]
