# Generated by Django 5.2.11 on 2026-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0003_pageseo_slug_alter_pageseo_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageseo",
            name="og_image_height",
            field=models.PositiveIntegerField(
                default=630, verbose_name="OG Image Height"
            ),
        ),
        migrations.AddField(
            model_name="pageseo",
            name="og_image_width",
            field=models.PositiveIntegerField(
                default=1200, verbose_name="OG Image Width"
            ),
        ),
        migrations.AddField(
            model_name="pageseo",
            name="og_type",
            field=models.CharField(
                choices=[("website", "Website"), ("article", "Article")],
                default="website",
                max_length=50,
                verbose_name="OG Type",
            ),
        ),
        migrations.AddField(
            model_name="pageseo",
            name="priority",
            field=models.FloatField(default=0.7, verbose_name="Sitemap Priority"),
        ),
        migrations.AddField(
            model_name="pageseo",
            name="robots",
            field=models.CharField(
                choices=[
                    ("index, follow", "Index, Follow"),
                    ("noindex, follow", "NoIndex, Follow"),
                    ("index, nofollow", "Index, NoFollow"),
                    ("noindex, nofollow", "NoIndex, NoFollow"),
                ],
                default="index, follow",
                max_length=50,
                verbose_name="Robots",
            ),
        ),
        migrations.AddField(
            model_name="pageseo",
            name="schema_type",
            field=models.CharField(
                choices=[
                    ("Organization", "Organization"),
                    ("Service", "Service"),
                    ("CreativeWork", "CreativeWork"),
                    ("WebPage", "WebPage"),
                ],
                default="WebPage",
                max_length=50,
                verbose_name="Schema Type",
            ),
        ),
        migrations.AddField(
            model_name="pageseo",
            name="twitter_card",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("summary_large_image", "Summary Large Image"),
                ],
                default="summary_large_image",
                max_length=50,
                verbose_name="Twitter Card",
            ),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="canonical",
            field=models.URLField(blank=True, verbose_name="Canonical URL"),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="og_description",
            field=models.TextField(blank=True, verbose_name="OG Description"),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="seo/", verbose_name="OG Image"
            ),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="og_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="OG Title"),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="page",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Головна сторінка"),
                    ("about", "Про компанію"),
                    ("contact", "Контакти"),
                    ("services", "Сторінка Послуг"),
                    ("portfolio", "Портфоліо"),
                ],
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Сторінка",
            ),
        ),
        migrations.AlterField(
            model_name="pageseo",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Slug сторінки",
            ),
        ),
    ]
