# Generated by Django 5.2.11 on 2026-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0004_pageseo_og_image_height_pageseo_og_image_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageseo",
            name="page",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Головна сторінка"),
                    ("about", "Про компанію"),
                    ("contact", "Контакти"),
                    ("services", "Сторінка Послуг"),
                    ("portfolio", "Портфоліо"),
                    ("gallery", "Галерея"),
                ],
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Сторінка",
            ),
        ),
    ]
