# Generated by Django 5.2.11 on 2026-04-28 14:00

import functools
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0005_alter_pageseo_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageseo",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    seo.models.upload_to_folder, *(), **{"folder": "seo"}
                ),
                verbose_name="OG Image",
            ),
        ),
    ]
